language: cpp

# The build matrix setup
# 2 configs * 3 OS = 6 builds.
# build both Release and Debug
env: 
 - BUILD_CONFIGURATION=Debug
 - BUILD_CONFIGURATION=Release

# run on all three OS
os: 
 - windows
 - linux
 - osx

# these elements are necessary to configure linux 
dist: xenial
compiler: gcc
addons: &gcc9
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-9', 'gcc-9','doxygen']

# this is an OSX specific setting
osx_image: xcode9.1

script:
   # On linux, configures to use recent C++ compiler + linker instead of default. 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export GCCVER='9' ; export CXX_COMPILER=g++-${GCCVER} C_COMPILER=gcc-${GCCVER} AR=gcc-ar-${GCCVER} RANLIB=gcc-ranlib-${GCCVER} NM=gcc-nm-${GCCVER} ; export CC=${C_COMPILER} CXX=${CXX_COMPILER} ; fi ;
  - mkdir -p build ; cd build
  - . ../.travis/build.sh
  - cd ..
  # Build documentation and copy it to website/ which is the folder we deploy to gh-pages 
  - if [[ "$TRAVIS_OS_NAME" == "linux" && $BUILD_CONFIGURATION = Debug ]]; then mkdir -p docs/html ; doxygen 2>&1 > doxygen.log || cat doxygen.log ; mkdir website ; cp -r docs/* website/ ; fi
  # copy the built binaries to the website folder
  - if [[ $BUILD_CONFIGURATION = Release ]]; then mkdir -p website ; cp -r build website ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && $BUILD_CONFIGURATION = Release ]]; then export BRANCH=linux ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" && $BUILD_CONFIGURATION = Release ]]; then export BRANCH=win ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && $BUILD_CONFIGURATION = Release ]]; then export BRANCH=osx ; fi
  - ls -lahR
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: $BRANCH
  local_dir: website/  
  on:
    branch: dev
    condition: $BUILD_CONFIGURATION = Release
